## Numpy

#### Numpy is abbraviated as Numerical Python. Unlike list numpy is faster. NumPy aims to provide an array object that is up to 50x faster that traditional Python lists, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [1]:
import numpy as np

In [2]:
# Creating arrays - Array is a container which can hold a fix number of items and these items should be of the same type.
arr= np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
type(arr)

numpy.ndarray

In [4]:
# ndarray - n dimensional array

In [5]:
np.__version__   # checking version

'1.18.5'

In [7]:
from numpy import random   # display random number

x = random.randint(100)

print(x)

82


In [9]:
from numpy import random  # display random float value between 0-1

x = random.rand()

print(x)

0.20930378807465977


In [11]:
from numpy import random    # display 10 random numbers

x=random.randint(100, size=(10))

print(x)

[99 81 60 67 78 66 84 78 96 16]


In [16]:
x= random.randint(10,100, 4)   # display 4 random numbers between 10-100
x

array([73, 64, 69, 36])

In [17]:
# Till now we worked only on 1-D array

In [18]:
# Generate 2-D array using random functio
s= random.randint(50, size=(3,5))   # 3 rows and 5 columns
s

array([[30,  5, 19, 15, 27],
       [23, 30, 29,  2,  1],
       [45, 36, 35, 39,  1]])

In [19]:
s= random.randint(50, size=(3,5,3))
s

array([[[28, 21, 46],
        [19, 49, 31],
        [ 6, 42, 35],
        [ 2, 15,  9],
        [43, 36, 14]],

       [[ 7, 26, 35],
        [31, 48,  8],
        [45,  9, 36],
        [11, 33,  7],
        [38,  9,  4]],

       [[ 3, 23,  2],
        [23, 35, 22],
        [25, 42, 18],
        [27, 20, 12],
        [24, 45, 26]]])

In [20]:
# choice() - it takes an array as a parameter and randomly returns one of the values.
s= random.choice([4,5,55,6])
s

6

In [24]:
s=random.choice(range(10,20))  # randomly displays a number range from 10-20
s

11

In [25]:
a=np.arange(15)  # displays number between 0-15 using arange() function
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
a=np.arange(15).reshape(3,5)  # creating 3 rows and 5 columns using reshape() function
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
print(a.shape)   # to find the shape
print(a.ndim)    # to find the n-dimension
print(a.size)    # to find the size
print(type(a))

(3, 5)
2
15
<class 'numpy.ndarray'>


In [31]:
a=np.linspace(0,9)   # To display random float values using linspace() function
a

array([0.        , 0.18367347, 0.36734694, 0.55102041, 0.73469388,
       0.91836735, 1.10204082, 1.28571429, 1.46938776, 1.65306122,
       1.83673469, 2.02040816, 2.20408163, 2.3877551 , 2.57142857,
       2.75510204, 2.93877551, 3.12244898, 3.30612245, 3.48979592,
       3.67346939, 3.85714286, 4.04081633, 4.2244898 , 4.40816327,
       4.59183673, 4.7755102 , 4.95918367, 5.14285714, 5.32653061,
       5.51020408, 5.69387755, 5.87755102, 6.06122449, 6.24489796,
       6.42857143, 6.6122449 , 6.79591837, 6.97959184, 7.16326531,
       7.34693878, 7.53061224, 7.71428571, 7.89795918, 8.08163265,
       8.26530612, 8.44897959, 8.63265306, 8.81632653, 9.        ])

In [36]:
a= np.linspace(0,9,3)    # To display random 3 float values using linspace() function( float values are stable)
a

array([0. , 4.5, 9. ])

In [44]:
a=np.arange(6)                  # 1-D dimension
print(a)
a=np.arange(9).reshape(3,3)     # 2-D dimension
print('-'*20)
print(a)
print('-'*20)
a=np.arange(24).reshape(2,3,4)  # 3-D dimension
print(a)

[0 1 2 3 4 5]
--------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [45]:
a=np.arange(36).reshape(2, 3, 6)   # 36 - must be mutiple of given number. (2,3,6), (2,6,3)
a


array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [47]:
a=np.arange(36).reshape(6, 2, 3)   # 36 - must be mutiple of given number. (2,3,6), (2,6,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35]]])